server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer-service/**
        - id: onboard-service
          uri: lb://onboard-service
          predicates:
              - Path=/onboard-service/**
        - id: file-service
          uri: lb://file-service
          predicates:
              - Path=/file-service/v1/file/**
        - id: bankadmin-service
          uri: lb://bankadmin-service
          predicates:
              - Path=/bankadmin-service/**
        - id: fundtransfer-service
          uri: lb://fundtransfer-service
          predicates:
            - Path=/fundtransfer-service/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/